In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

In [ ]:
import joblib
df_train = joblib.load('/content/drive/MyDrive/Project/4.Microsoft/encoded_train_data.joblib')
df_train.head()

IncidentGrade  AlertTitle_1  AlertTitle_2  AlertTitle_3  AlertTitle_4  \
0              0         False         False         False         False   
1              0         False         False         False         False   
2              0         False         False         False         False   
3              2         False         False         False         False   
4              0         False         False         False         False   

   AlertTitle_Others  Category_CommandAndControl  Category_CredentialAccess  \
0               True                       False                      False   
1               True                       False                      False   
2               True                       False                      False   
3               True                       False                      False   
4               True                       False                      False   

   Category_CredentialStealing  Category_DefenseEvasion  Category_Discovery  \
0                        False                    False               False   
1                        False                    False               False   
2                        False                    False               False   
3                        False                    False               False   
4                        False                    False               False   

   Category_Execution  Category_Exfiltration  Category_Exploit  \
0               False                  False             False   
1               False                  False             False   
2                True                  False             False   
3               False                  False             False   
4               False                   True             False   

   Category_Impact  Category_InitialAccess  Category_LateralMovement  \
0            False                   False                     False   
1             True                   False                     False   
2            False                   False                     False   
3            False                   False                     False   
4            False                   False                     False   

   Category_Malware  Category_Persistence  Category_PrivilegeEscalation  \
0              True                 False                         False   
1             False                 False                         False   
2             False                 False                         False   
3             False                 False                         False   
4             False                 False                         False   

   Category_Ransomware  Category_SuspiciousActivity  \
0                False                        False   
1                False                        False   
2                False                        False   
3                False                         True   
4                False                        False   

   Category_UnwantedSoftware  Category_WebExploit  EntityType_AmazonResource  \
0                      False                False                      False   
1                      False                False                      False   
2                      False                False                      False   
3                      False                False                      False   
4                      False                False                      False   

   EntityType_AzureResource  EntityType_Blob  EntityType_BlobContainer  \
0                     False            False                     False   
1                     False            False                     False   
2                     False            False                     False   
3                     False            False                     False   
4                     False            False                     False   

   EntityType_CloudApplication  EntityType_CloudLogonReque

In [ ]:
df_train.shape

(4577400, 73)

In [ ]:
from sklearn.model_selection import train_test_split

# Separateing features (X) and target variable (y)
X = df_train.drop(columns=['IncidentGrade'])
y = df_train['IncidentGrade']

# Spliting the data (80:20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
print("y_train: ",y_train.value_counts())
print("\n")
print("y_test: ",y_test.value_counts())

y_train:  IncidentGrade
0    1579154
2    1287166
1     795600
Name: count, dtype: int64


y_test:  IncidentGrade
0    394789
2    321791
1    198900
Name: count, dtype: int64


## Choosing the Best Model

In [ ]:
from sklearn.metrics import classification_report

### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

# Logistic Regression Model
lr = LogisticRegression(class_weight='balanced', random_state=42)

# Training the Logistic Regression model
print("\nTraining Logistic Regression...")
lr.fit(X_train, y_train)

# Predicting on the validation set
y_pred_train_lr = lr.predict(X_train)
y_pred_test_lr = lr.predict(X_test)

# Classification Report for Logistic Regression
print("Logistic Regression Classification Report for Train :\n", classification_report(y_train, y_pred_train_lr, target_names=['Class 0', 'Class 1', 'Class 2']))
print("-----------------------------------------------------------------------")
print("Logistic Regression Classification Report for Test :\n", classification_report(y_test, y_pred_test_lr, target_names=['Class 0', 'Class 1', 'Class 2']))


Training Logistic Regression...
Logistic Regression Classification Report for Train :
               precision    recall  f1-score   support

     Class 0       0.64      0.58      0.61   1579154
     Class 1       0.31      0.44      0.36    795600
     Class 2       0.68      0.59      0.63   1287166

    accuracy                           0.55   3661920
   macro avg       0.54      0.53      0.53   3661920
weighted avg       0.58      0.55      0.56   3661920

-----------------------------------------------------------------------
Logistic Regression Classification Report for Test :
               precision    recall  f1-score   support

     Class 0       0.64      0.58      0.61    394789
     Class 1       0.31      0.44      0.36    198900
     Class 2       0.68      0.58      0.63    321791

    accuracy                           0.55    915480
   macro avg       0.54      0.53      0.53    915480
weighted avg       0.58      0.55      0.56    915480



### Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Decision Tree Classifier Model
dt = DecisionTreeClassifier(class_weight='balanced', random_state=42)

# Training the Decision Tree Classifier model
print("\nTraining Decision Tree Classifier...")
dt.fit(X_train, y_train)

# Predicting on the validation set
y_pred_train_dt = dt.predict(X_train)
y_pred_test_dt = dt.predict(X_test)

# Classification Report for Decision Tree Classifier
print("Decision Tree Classifier Classification Report for Train :\n", classification_report(y_train, y_pred_train_dt, target_names=['Class 0', 'Class 1', 'Class 2']))
print("-----------------------------------------------------------------------")
print("Decision Tree Classifier Classification Report for Test :\n", classification_report(y_test, y_pred_test_dt, target_names=['Class 0', 'Class 1', 'Class 2']))



Training Decision Tree Classifier...
Decision Tree Classifier Classification Report for Train :
               precision    recall  f1-score   support

     Class 0       0.65      0.72      0.68   1579154
     Class 1       0.40      0.38      0.39    795600
     Class 2       0.68      0.60      0.64   1287166

    accuracy                           0.61   3661920
   macro avg       0.57      0.57      0.57   3661920
weighted avg       0.60      0.61      0.60   3661920

-----------------------------------------------------------------------
Decision Tree Classifier Classification Report for Test :
               precision    recall  f1-score   support

     Class 0       0.65      0.72      0.68    394789
     Class 1       0.40      0.38      0.39    198900
     Class 2       0.68      0.61      0.64    321791

    accuracy                           0.61    915480
   macro avg       0.58      0.57      0.57    915480
weighted avg       0.60      0.61      0.60    915480



### Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(class_weight='balanced', random_state=42)

print("\nTraining Random Forest Classifier...")
rf.fit(X_train, y_train)

y_pred_train_rf = rf.predict(X_train)
y_pred_test_rf = rf.predict(X_test)

print("Random Forest Classifier Classification Report for Train :\n", classification_report(y_train, y_pred_train_rf, target_names=['Class 0', 'Class 1', 'Class 2']))
print("-----------------------------------------------------------------------")
print("Random Forest Classifier Classification Report for Test :\n", classification_report(y_test, y_pred_test_rf, target_names=['Class 0', 'Class 1', 'Class 2']))



Training Random Forest Classifier...
Random Forest Classifier Classification Report for Train :
               precision    recall  f1-score   support

     Class 0       0.65      0.72      0.68   1579154
     Class 1       0.40      0.38      0.39    795600
     Class 2       0.68      0.60      0.64   1287166

    accuracy                           0.61   3661920
   macro avg       0.57      0.57      0.57   3661920
weighted avg       0.60      0.61      0.60   3661920

-----------------------------------------------------------------------
Random Forest Classifier Classification Report for Test :
               precision    recall  f1-score   support

     Class 0       0.65      0.72      0.68    394789
     Class 1       0.40      0.38      0.39    198900
     Class 2       0.68      0.61      0.64    321791

    accuracy                           0.61    915480
   macro avg       0.58      0.57      0.57    915480
weighted avg       0.60      0.61      0.60    915480



### Lightgbm

In [ ]:
import lightgbm as lgb

# LightGBM Classifier
lgbm = lgb.LGBMClassifier(random_state=42)

print("\nTraining LightGBM Classifier...")
lgbm.fit(X_train, y_train)

y_pred_train_lgbm = lgbm.predict(X_train)
y_pred_test_lgbm = lgbm.predict(X_test)

print("LightGBM Classifier Classification Report for Train :\n", classification_report(y_train, y_pred_train_lgbm, target_names=['Class 0', 'Class 1', 'Class 2']))
print("-----------------------------------------------------------------------")
print("LightGBM Classifier Classification Report for Test :\n", classification_report(y_test, y_pred_test_lgbm, target_names=['Class 0', 'Class 1', 'Class 2']))



Training LightGBM Classifier...
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.344479 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 134
[LightGBM] [Info] Number of data points in the train set: 3661920, number of used features: 67
[LightGBM] [Info] Start training from score -0.841098
[LightGBM] [Info] Start training from score -1.526646
[LightGBM] [Info] Start training from score -1.045545
LightGBM Classifier Classification Report for Train :
               precision    recall  f1-score   support

     Class 0       0.60      0.90      0.72   1579154
     Class 1       0.65      0.17      0.27    795600
     Class 2       0.71      0.60      0.65   1287166

    accuracy                           0.63   3661920
   macro avg       0.65      0.55      0.55   3661920
weighted avg       0.65      0.63      0.60   3661920

---------------

### XGBoost

In [ ]:
import xgboost as xgb

# XGBoost Classifier
xg = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')

print("\nTraining XGBoost Classifier...")
xg.fit(X_train, y_train)

y_pred_train_xg = xg.predict(X_train)
y_pred_test_xg = xg.predict(X_test)

print("XGBoost Classifier Classification Report for Train :\n", classification_report(y_train, y_pred_train_xg, target_names=['Class 0', 'Class 1', 'Class 2']))
print("-----------------------------------------------------------------------")
print("XGBoost Classifier Classification Report for Test :\n", classification_report(y_test, y_pred_test_xg, target_names=['Class 0', 'Class 1', 'Class 2']))



Training XGBoost Classifier...
XGBoost Classifier Classification Report for Train :
               precision    recall  f1-score   support

     Class 0       0.60      0.90      0.72   1579154
     Class 1       0.65      0.17      0.27    795600
     Class 2       0.71      0.60      0.65   1287166

    accuracy                           0.63   3661920
   macro avg       0.65      0.55      0.54   3661920
weighted avg       0.65      0.63      0.60   3661920

-----------------------------------------------------------------------
XGBoost Classifier Classification Report for Test :
               precision    recall  f1-score   support

     Class 0       0.60      0.90      0.72    394789
     Class 1       0.65      0.17      0.27    198900
     Class 2       0.72      0.60      0.65    321791

    accuracy                           0.63    915480
   macro avg       0.65      0.55      0.55    915480
weighted avg       0.65      0.63      0.60    915480



In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def get_metrics(y_true, y_pred):
  accuracy = accuracy_score(y_true, y_pred)
  precision = precision_score(y_true, y_pred, average='macro')
  recall = recall_score(y_true, y_pred, average='macro')
  f1 = f1_score(y_true, y_pred, average='macro')
  return accuracy, precision, recall, f1

# Logistic Regression
accuracy_lr, precision_lr, recall_lr, f1_lr = get_metrics(y_test, y_pred_test_lr)
print("Logistic Regression - Accuracy:", accuracy_lr, "Precision:", precision_lr, "Recall:", recall_lr, "Macro F1-score:", f1_lr)


# Decision Tree
accuracy_dt, precision_dt, recall_dt, f1_dt = get_metrics(y_test, y_pred_test_dt)
print("Decision Tree - Accuracy:", accuracy_dt, "Precision:", precision_dt, "Recall:", recall_dt, "Macro F1-score:", f1_dt)

# Random Forest
accuracy_rf, precision_rf, recall_rf, f1_rf = get_metrics(y_test, y_pred_test_rf)
print("Random Forest - Accuracy:", accuracy_rf, "Precision:", precision_rf, "Recall:", recall_rf, "Macro F1-score:", f1_rf)

# LightGBM
accuracy_lgbm, precision_lgbm, recall_lgbm, f1_lgbm = get_metrics(y_test, y_pred_test_lgbm)
print("LightGBM - Accuracy:", accuracy_lgbm, "Precision:", precision_lgbm, "Recall:", recall_lgbm, "Macro F1-score:", f1_lgbm)

# XGBoost
accuracy_xg, precision_xg, recall_xg, f1_xg = get_metrics(y_test, y_pred_test_xg)
print("XGBoost - Accuracy:", accuracy_xg, "Precision:", precision_xg, "Recall:", recall_xg, "Macro F1-score:", f1_xg)


Logistic Regression - Accuracy: 0.5516461309913925 Precision: 0.5434930747241401 Recall: 0.534710754873344 Macro F1-score: 0.5339842450274235
Decision Tree - Accuracy: 0.6057423428146983 Precision: 0.5750468456251513 Recall: 0.5687027289833089 Macro F1-score: 0.5705196570368208
Random Forest - Accuracy: 0.6057609123082973 Precision: 0.575059288889766 Recall: 0.5687095986819276 Macro F1-score: 0.5705276073321951
LightGBM - Accuracy: 0.6342224843797789 Precision: 0.6533236894305449 Recall: 0.5554244130181171 Macro F1-score: 0.5463668211157526
XGBoost - Accuracy: 0.6341733298378992 Precision: 0.6537869751995743 Recall: 0.5549629482339626 Macro F1-score: 0.5454282790047821


In [ ]:
data = {
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest', 'LightGBM', 'XGBoost'],
    'Accuracy': [0.5516461309913925, 0.6057423428146983, 0.6057609123082973, 0.6342224843797789, 0.6341733298378992],
    'Precision': [0.5434930747241401, 0.5750468456251513, 0.575059288889766, 0.6533236894305449, 0.6537869751995743],
    'Recall': [0.534710754873344, 0.5687027289833089, 0.5687095986819276, 0.5554244130181171, 0.5549629482339626],
    'Macro F1-score': [0.5339842450274235, 0.5705196570368208, 0.5705276073321951, 0.5463668211157526, 0.5454282790047821]
}

df = pd.DataFrame(data)
df


Model  Accuracy  Precision    Recall  Macro F1-score
0  Logistic Regression  0.551646   0.543493  0.534711        0.533984
1        Decision Tree  0.605742   0.575047  0.568703        0.570520
2        Random Forest  0.605761   0.575059  0.568710        0.570528
3             LightGBM  0.634222   0.653324  0.555424        0.546367
4              XGBoost  0.634173   0.653787  0.554963        0.545428

In [ ]:
print("Comparison Table:")
print(df.to_string(index=False))
best_models_with_max_f1 = df[df['Macro F1-score'] == df['Macro F1-score'].max()]
if len(best_models_with_max_f1) > 1:
    best_model = best_models_with_max_f1.loc[best_models_with_max_f1['Accuracy'].idxmax()]
else:
    best_model = df.loc[df['Macro F1-score'].idxmax()]
print("\nBest Model Based on Macro-F1 Score (and Accuracy in case of a tie):")
best_model


Comparison Table:
              Model  Accuracy  Precision   Recall  Macro F1-score
Logistic Regression  0.551646   0.543493 0.534711        0.533984
      Decision Tree  0.605742   0.575047 0.568703        0.570520
      Random Forest  0.605761   0.575059 0.568710        0.570528
           LightGBM  0.634222   0.653324 0.555424        0.546367
            XGBoost  0.634173   0.653787 0.554963        0.545428

Best Model Based on Macro-F1 Score (and Accuracy in case of a tie):


Model             Random Forest
Accuracy               0.605761
Precision              0.575059
Recall                  0.56871
Macro F1-score         0.570528
Name: 2, dtype: object

# Applying Smote

In [ ]:
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Loading the encoded train data
# df_train = joblib.load('encoded_train_data.joblib', mmap_mode='r')

In [ ]:
# Separating the features (X) and target variable (y)
X = df_train.drop('IncidentGrade', axis=1)
y = df_train['IncidentGrade']

# Convert all columns to numeric, coercing errors
X = X.apply(pd.to_numeric, errors='coerce')

# Drop columns with NaN values
X = X.dropna(axis=1)


In [ ]:
# Splitting the data into training (80%) and validation (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# Downsampling the training data to 2% for quicker processing
X_train_sampled, _, y_train_sampled, _ = train_test_split(X_train, y_train, train_size=0.02, stratify=y_train, random_state=42)

# Convert boolean columns to integers if they exist
if X_train_sampled.select_dtypes(include=['bool']).shape[1] > 0:
    X_train_sampled = X_train_sampled.astype(int)

In [ ]:
# Applying SMOTE to balance the dataset
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_sampled, y_train_sampled)

In [ ]:
# Hyperparameters for RandomizedSearchCV
param_dist = {
    'n_estimators': [50, 75],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}


# Random Forest Classifier
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

# Randomized Search CV for hyperparameter tuning
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, n_iter=5,
                                   cv=3, verbose=1, random_state=42, n_jobs=-1)

# Fitting the Randomized Search with resampled training data
random_search.fit(X_train_resampled, y_train_resampled)

# Best parameters and model
best_rf = random_search.best_estimator_

# Predict on validation set
y_pred = best_rf.predict(X_test)




# Print results
print("Best Hyperparameters:", random_search.best_params_)
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Fitting 3 folds for each of 5 candidates, totalling 15 fits
Best Hyperparameters: {'n_estimators': 50, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': None, 'bootstrap': False}
Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.67      0.66    394789
           1       0.38      0.39      0.39    198900
           2       0.66      0.63      0.64    321791

    accuracy                           0.60    915480
   macro avg       0.57      0.56      0.57    915480
weighted avg       0.60      0.60      0.60    915480

Confusion Matrix:
[[264960  73935  55894]
 [ 71895  78054  48951]
 [ 66784  52201 202806]]


In [ ]:
import joblib
joblib.dump(best_rf, '/content/drive/MyDrive/Project/4.Microsoft/rf_smote_tuned_model.joblib')

['/content/drive/MyDrive/Project/4.Microsoft/rf_smote_tuned_model.joblib']

## Without Smote

In [ ]:
# Separating the features (X) and target variable (y)
X = df_train.drop('IncidentGrade', axis=1)
y = df_train['IncidentGrade']

# Convert all columns to numeric, coercing errors
X = X.apply(pd.to_numeric, errors='coerce')

# Drop columns with NaN values
X = X.dropna(axis=1)

In [ ]:
# Splitting the data into training (80%) and validation (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# Downsampling the training data to 2% for quicker processing
X_train_sampled, _, y_train_sampled, _ = train_test_split(X_train, y_train, train_size=0.02, stratify=y_train, random_state=42)


In [ ]:
# Convert boolean columns to integers if they exist
if X_train_sampled.select_dtypes(include=['bool']).shape[1] > 0:
  X_train_sampled = X_train_sampled.astype(int)

In [ ]:
# Random Forest Classifier
rf_no_smote  = RandomForestClassifier(random_state=42, n_jobs=-1)

# Hyperparameters for RandomizedSearchCV
param_dist = {
    'n_estimators': [50, 75],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}

# Randomized Search CV for hyperparameter tuning
rf_no_smote = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, n_iter=5,
                                   cv=3, verbose=1, random_state=42, n_jobs=-1)

# Fitting the Randomized Search with sampled training data
rf_no_smote.fit(X_train_sampled, y_train_sampled)

# Best parameters and model
best_rf = rf_no_smote.best_estimator_

# Predict on validation set
y_pred_no_smote = best_rf.predict(X_test)

# Print results
print("Best Hyperparameters:", rf_no_smote.best_params_)
print("Classification Report:")
print(classification_report(y_test, y_pred_no_smote))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_no_smote))


Fitting 3 folds for each of 5 candidates, totalling 15 fits
Best Hyperparameters: {'n_estimators': 75, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_depth': None, 'bootstrap': False}
Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.91      0.72    394789
           1       0.63      0.18      0.28    198900
           2       0.73      0.58      0.65    321791

    accuracy                           0.63    915480
   macro avg       0.65      0.55      0.55    915480
weighted avg       0.65      0.63      0.60    915480

Confusion Matrix:
[[358324  13197  23268]
 [117797  35426  45677]
 [127937   7555 186299]]


In [ ]:
joblib.dump(rf_no_smote, '/content/drive/MyDrive/Project/4.Microsoft/rf_no_smote_tuned_model.joblib')

['/content/drive/MyDrive/Project/4.Microsoft/rf_no_smote_tuned_model.joblib']

# Evaluating on Test Data

## Doing with smote

In [ ]:
# Loading the saved Random Forest model
best_rf = joblib.load("/content/drive/MyDrive/Project/4.Microsoft/rf_smote_tuned_model.joblib")

# Loading the test dataset
test_data = joblib.load('/content/drive/MyDrive/Project/4.Microsoft/encoded_test_data.joblib')

# Separateing the features and target from test data
X_test = test_data.drop('IncidentGrade', axis=1)
y_test = test_data['IncidentGrade']

In [ ]:
# Makeing predictions on the test data
y_test_pred = best_rf.predict(X_test)

# Evaluateing the saved model on the test data
print("\nClassification Report on Test Data:")
report = classification_report(y_test, y_test_pred, output_dict=True)
print(classification_report(y_test, y_test_pred))

macro_f1 = report['macro avg']['f1-score']
macro_precision = report['macro avg']['precision']
macro_recall = report['macro avg']['recall']

print("\nMacro-F1 Score: {:.2f}".format(macro_f1))
print("Macro Precision: {:.2f}".format(macro_precision))
print("Macro Recall: {:.2f}".format(macro_recall))
print("\nConfusion Matrix on Test Data:")
print(confusion_matrix(y_test, y_test_pred))


Classification Report on Test Data:
              precision    recall  f1-score   support

           0       0.67      0.67      0.67   1630942
           1       0.42      0.44      0.43    868897
           2       0.69      0.67      0.68   1422856

    accuracy                           0.62   3922695
   macro avg       0.59      0.59      0.59   3922695
weighted avg       0.62      0.62      0.62   3922695


Macro-F1 Score: 0.59
Macro Precision: 0.59
Macro Recall: 0.59

Confusion Matrix on Test Data:
[[1098229  311957  220756]
 [ 278941  379669  210287]
 [ 267357  204508  950991]]


## Doing without smote

In [ ]:
# Loading the saved Random Forest model
best_rf = joblib.load("/content/drive/MyDrive/Project/4.Microsoft/rf_no_smote_tuned_model.joblib")

# Loading the test dataset
test_data = joblib.load('/content/drive/MyDrive/Project/4.Microsoft/encoded_test_data.joblib')

# Separateing the features and target from test data
X_test = test_data.drop('IncidentGrade', axis=1)
y_test = test_data['IncidentGrade']

In [ ]:
# Makeing predictions on the test data
y_test_pred = best_rf.predict(X_test)

# Evaluateing the saved model on the test data
print("\nClassification Report on Test Data:")
report = classification_report(y_test, y_test_pred, output_dict=True)
print(classification_report(y_test, y_test_pred))

macro_f1 = report['macro avg']['f1-score']
macro_precision = report['macro avg']['precision']
macro_recall = report['macro avg']['recall']

print("\nMacro-F1 Score: {:.2f}".format(macro_f1))
print("Macro Precision: {:.2f}".format(macro_precision))
print("Macro Recall: {:.2f}".format(macro_recall))
print("\nConfusion Matrix on Test Data:")
print(confusion_matrix(y_test, y_test_pred))


Classification Report on Test Data:
              precision    recall  f1-score   support

           0       0.60      0.90      0.72   1630942
           1       0.65      0.21      0.32    868897
           2       0.75      0.62      0.68   1422856

    accuracy                           0.65   3922695
   macro avg       0.66      0.58      0.57   3922695
weighted avg       0.66      0.65      0.61   3922695


Macro-F1 Score: 0.57
Macro Precision: 0.66
Macro Recall: 0.58

Confusion Matrix on Test Data:
[[1467764   67280   95898]
 [ 487514  182287  199096]
 [ 509550   32039  881267]]
