In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

In [ ]:
!pip install joblib
import joblib

In [ ]:
import joblib
df_train = joblib.load('/content/drive/MyDrive/Project/4.Microsoft/New/df_train.joblib')
df_train.head()

Sha256  IpAddress  NetworkMessageId  RegistryKey  RegistryValueName  \
0    1296     360606            529644         1631                635   
1  138268     360606            529644         1631                635   
2  138268     360606            529644         1631                635   
3  138268     360606            529644         1631                635   
4  138268     360606            529644         1631                635   

   RegistryValueData  ApplicationId  OAuthApplicationId  OSVersion  \
0                860           2251                 881         66   
1                860           2251                 881         66   
2                860           2251                 881         66   
3                860           2251                 881         66   
4                860           2251                 881         66   

   IncidentGrade  AlertTitle_1  AlertTitle_2  AlertTitle_3  AlertTitle_4  \
0              0         False         False         False         False   
1              0         False         False         False         False   
2              0         False         False         False         False   
3              2         False         False         False         False   
4              0         False         False         False         False   

   AlertTitle_Others  Category_CommandAndControl  Category_CredentialAccess  \
0               True                       False                      False   
1               True                       False                      False   
2               True                       False                      False   
3               True                       False                      False   
4               True                       False                      False   

   Category_CredentialStealing  Category_DefenseEvasion  Category_Discovery  \
0                        False                    False               False   
1                        False                    False               False   
2                        False                    False               False   
3                        False                    False               False   
4                        False                    False               False   

   Category_Execution  Category_Exfiltration  Category_Exploit  \
0               False                  False             False   
1               False                  False             False   
2                True                  False             False   
3               False                  False             False   
4               False                   True             False   

   Category_Impact  Category_InitialAccess  Category_LateralMovement  \
0            False                   False                     False   
1             True                   False                     False   
2            False                   False                     False   
3            False                   False                     False   
4            False                   False                     False   

   Category_Malware  Category_Persistence  Category_PrivilegeEscalation  \
0              True                 False                         False   
1             False                 False                         False   
2             False                 False                         False   
3             False                 False                         False   
4             False                 False                         False   

   Category_Ransomware  Category_SuspiciousActivity  \
0                False                        False   
1                False                        False   
2                False                        False   
3                False                         True   
4                False                        False   

   Category_UnwantedSoftware  Category_WebExploit  EntityType_AmazonResource  \
0                      False          

In [ ]:
import joblib
df_test = joblib.load('/content/drive/MyDrive/Project/4.Microsoft/New/df_test.joblib')
df_test.head()

Sha256  IpAddress  NetworkMessageId  RegistryKey  RegistryValueName  \
0  138268     360606            529644         1631                635   
1  138268     360606            529644         1631                635   
2    4296     360606            529644         1631                635   
3  138268     360606            529644         1631                635   
4  138268     360606            529644         1631                635   

   RegistryValueData  ApplicationId  OAuthApplicationId  OSVersion  \
0                860           2251                 881         66   
1                860           2251                 881          0   
2                860           2251                 881         66   
3                860           2251                 881         66   
4                860           2251                 881         66   

   IncidentGrade  AlertTitle_1  AlertTitle_2  AlertTitle_3  AlertTitle_4  \
0              0         False         False         False         False   
1              0         False          True         False         False   
2              0         False         False         False         False   
3              1         False         False         False         False   
4              0         False         False         False         False   

   AlertTitle_Others  Category_CommandAndControl  Category_CredentialAccess  \
0               True                       False                      False   
1              False                        True                      False   
2               True                       False                      False   
3              False                       False                      False   
4               True                       False                      False   

   Category_CredentialStealing  Category_DefenseEvasion  Category_Discovery  \
0                        False                    False               False   
1                        False                    False               False   
2                        False                    False               False   
3                        False                    False               False   
4                        False                    False                True   

   Category_Execution  Category_Exfiltration  Category_Exploit  \
0               False                  False             False   
1               False                  False             False   
2               False                  False             False   
3               False                  False             False   
4               False                  False             False   

   Category_Impact  Category_InitialAccess  Category_LateralMovement  \
0            False                   False                      True   
1            False                   False                     False   
2            False                   False                      True   
3            False                    True                     False   
4            False                   False                     False   

   Category_Malware  Category_Persistence  Category_PrivilegeEscalation  \
0             False                 False                         False   
1             False                 False                         False   
2             False                 False                         False   
3             False                 False                         False   
4             False                 False                         False   

   Category_Ransomware  Category_SuspiciousActivity  \
0                False                        False   
1                False                        False   
2                False                        False   
3                False                        False   
4                False                        False   

   Category_UnwantedSoftware  Category_WebExploit  EntityType_AmazonResource  \
0                      False          

In [ ]:
from sklearn.model_selection import train_test_split

# Separateing features (X) and target variable (y)
X = df_train.drop(columns=['IncidentGrade'])
y = df_train['IncidentGrade']

# Spliting the data (80:30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [ ]:
print("y_train: ",y_train.value_counts())
print("\n")
print("y_test: ",y_test.value_counts())

y_train:  IncidentGrade
0    1381760
2    1126270
1     696150
Name: count, dtype: int64


y_test:  IncidentGrade
0    592183
2    482687
1    298350
Name: count, dtype: int64


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
import xgboost as xgb

# XGBoost Classifier
xg = xgb.XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')

print("\nTraining XGBoost Classifier...")
xg.fit(X_train, y_train)

y_pred_train_xg = xg.predict(X_train)
y_pred_test_xg = xg.predict(X_test)

print("XGBoost Classifier Classification Report for Train :\n", classification_report(y_train, y_pred_train_xg, target_names=['Class 0', 'Class 1', 'Class 2']))
print("-----------------------------------------------------------------------")
print("XGBoost Classifier Classification Report for Test :\n", classification_report(y_test, y_pred_test_xg, target_names=['Class 0', 'Class 1', 'Class 2']))



Training XGBoost Classifier...
XGBoost Classifier Classification Report for Train :
               precision    recall  f1-score   support

     Class 0       0.61      0.90      0.73   1381760
     Class 1       0.75      0.25      0.37    696150
     Class 2       0.74      0.62      0.67   1126270

    accuracy                           0.66   3204180
   macro avg       0.70      0.59      0.59   3204180
weighted avg       0.69      0.66      0.63   3204180

-----------------------------------------------------------------------
XGBoost Classifier Classification Report for Test :
               precision    recall  f1-score   support

     Class 0       0.61      0.90      0.73    592183
     Class 1       0.75      0.25      0.37    298350
     Class 2       0.74      0.62      0.67    482687

    accuracy                           0.66   1373220
   macro avg       0.70      0.59      0.59   1373220
weighted avg       0.69      0.66      0.63   1373220



In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(class_weight='balanced', random_state=42)

print("\nTraining Random Forest Classifier...")
rf.fit(X_train, y_train)

y_pred_train_rf = rf.predict(X_train)
y_pred_test_rf = rf.predict(X_test)

print("Random Forest Classifier Classification Report for Train :\n", classification_report(y_train, y_pred_train_rf, target_names=['Class 0', 'Class 1', 'Class 2']))
print("-----------------------------------------------------------------------")
print("Random Forest Classifier Classification Report for Test :\n", classification_report(y_test, y_pred_test_rf, target_names=['Class 0', 'Class 1', 'Class 2']))


Training Random Forest Classifier...
Random Forest Classifier Classification Report for Train :
               precision    recall  f1-score   support

     Class 0       0.75      0.83      0.79   1381760
     Class 1       0.66      0.58      0.62    696150
     Class 2       0.76      0.72      0.74   1126270

    accuracy                           0.74   3204180
   macro avg       0.72      0.71      0.71   3204180
weighted avg       0.73      0.74      0.73   3204180

-----------------------------------------------------------------------
Random Forest Classifier Classification Report for Test :
               precision    recall  f1-score   support

     Class 0       0.71      0.79      0.74    592183
     Class 1       0.58      0.51      0.54    298350
     Class 2       0.72      0.67      0.69    482687

    accuracy                           0.69   1373220
   macro avg       0.67      0.66      0.66   1373220
weighted avg       0.68      0.69      0.68   1373220



# Applying Smote

In [ ]:
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Loading the encoded train data
# df_train = joblib.load('encoded_train_data.joblib', mmap_mode='r')

In [ ]:
# Separating the features (X) and target variable (y)
X = df_train.drop('IncidentGrade', axis=1)
y = df_train['IncidentGrade']

# Convert all columns to numeric, coercing errors
X = X.apply(pd.to_numeric, errors='coerce')

# Drop columns with NaN values
X = X.dropna(axis=1)


In [ ]:
# Splitting the data into training (80%) and validation (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# Downsampling the training data to 2% for quicker processing
X_train_sampled, _, y_train_sampled, _ = train_test_split(X_train, y_train, train_size=0.02, stratify=y_train, random_state=42)

# Convert boolean columns to integers if they exist
if X_train_sampled.select_dtypes(include=['bool']).shape[1] > 0:
    X_train_sampled = X_train_sampled.astype(int)

In [ ]:
# Applying SMOTE to balance the dataset
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_sampled, y_train_sampled)

In [ ]:
# Hyperparameters for RandomizedSearchCV
param_dist = {
    'n_estimators': [50,100,200,500],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}


# Random Forest Classifier
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

# Randomized Search CV for hyperparameter tuning
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, n_iter=5,
                                   cv=3, verbose=1, random_state=42, n_jobs=-1)

# Fitting the Randomized Search with resampled training data
random_search.fit(X_train_resampled, y_train_resampled)

# Best parameters and model
best_rf = random_search.best_estimator_

# Predict on validation set
y_pred = best_rf.predict(X_test)




# Print results
print("Best Hyperparameters:", random_search.best_params_)
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Fitting 3 folds for each of 5 candidates, totalling 15 fits
Best Hyperparameters: {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_depth': 20, 'bootstrap': False}
Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.79      0.71    394789
           1       0.50      0.36      0.42    198900
           2       0.70      0.64      0.67    321791

    accuracy                           0.65    915480
   macro avg       0.62      0.60      0.60    915480
weighted avg       0.64      0.65      0.64    915480

Confusion Matrix:
[[311367  43497  39925]
 [ 79518  72295  47087]
 [ 87012  27550 207229]]


In [ ]:
import joblib
joblib.dump(best_rf,'rf_smote_tuned_model.joblib')

['rf_smote_tuned_model.joblib']

# Without smote

In [ ]:
# Separating the features (X) and target variable (y)
X = df_train.drop('IncidentGrade', axis=1)
y = df_train['IncidentGrade']

# Convert all columns to numeric, coercing errors
X = X.apply(pd.to_numeric, errors='coerce')

# Drop columns with NaN values
X = X.dropna(axis=1)

In [ ]:
# Splitting the data into training (80%) and validation (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
# Downsampling the training data to 2% for quicker processing
X_train_sampled, _, y_train_sampled, _ = train_test_split(X_train, y_train, train_size=0.02, stratify=y_train, random_state=42)


In [ ]:
# Convert boolean columns to integers if they exist
if X_train_sampled.select_dtypes(include=['bool']).shape[1] > 0:
  X_train_sampled = X_train_sampled.astype(int)

In [ ]:
# Hyperparameters for RandomizedSearchCV
param_dist = {
    'n_estimators': [50,100,200,500],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}


# Random Forest Classifier
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

# Randomized Search CV for hyperparameter tuning
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, n_iter=5,
                                   cv=3, verbose=1, random_state=42, n_jobs=-1)

# Fitting the Randomized Search with resampled training data
random_search.fit(X_train_resampled, y_train_resampled)

# Best parameters and model
best_rf = random_search.best_estimator_

# Predict on validation set
y_pred = best_rf.predict(X_test)




# Print results
print("Best Hyperparameters:", random_search.best_params_)
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Fitting 3 folds for each of 5 candidates, totalling 15 fits
Best Hyperparameters: {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_depth': 20, 'bootstrap': False}
Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.79      0.71    394789
           1       0.50      0.36      0.42    198900
           2       0.70      0.64      0.67    321791

    accuracy                           0.65    915480
   macro avg       0.62      0.60      0.60    915480
weighted avg       0.64      0.65      0.64    915480

Confusion Matrix:
[[311367  43497  39925]
 [ 79518  72295  47087]
 [ 87012  27550 207229]]


In [ ]:
import joblib
joblib.dump(best_rf,'rf_no_smote_tuned_model.joblib')

['rf_no_smote_tuned_model.joblib']

# Testing on Test Data

## Doing with smote

In [ ]:
# Loading the saved Random Forest model
best_rf = joblib.load("/content/drive/MyDrive/Project/4.Microsoft/New/rf_smote_tuned_model.joblib")

# Loading the test dataset
test_data = joblib.load('/content/drive/MyDrive/Project/4.Microsoft/New/df_test.joblib')

# Separateing the features and target from test data
X_test = test_data.drop('IncidentGrade', axis=1)
y_test = test_data['IncidentGrade']

In [ ]:
# Makeing predictions on the test data
y_test_pred = best_rf.predict(X_test)

# Evaluateing the saved model on the test data
print("\nClassification Report on Test Data:")
report = classification_report(y_test, y_test_pred, output_dict=True)
print(classification_report(y_test, y_test_pred))

macro_f1 = report['macro avg']['f1-score']
macro_precision = report['macro avg']['precision']
macro_recall = report['macro avg']['recall']

print("\nMacro-F1 Score: {:.2f}".format(macro_f1))
print("Macro Precision: {:.2f}".format(macro_precision))
print("Macro Recall: {:.2f}".format(macro_recall))
print("\nConfusion Matrix on Test Data:")
print(confusion_matrix(y_test, y_test_pred))


Classification Report on Test Data:
              precision    recall  f1-score   support

           0       0.65      0.78      0.71   1630942
           1       0.53      0.38      0.44    868897
           2       0.73      0.68      0.70   1422856

    accuracy                           0.66   3922695
   macro avg       0.64      0.62      0.62   3922695
weighted avg       0.65      0.66      0.65   3922695


Macro-F1 Score: 0.62
Macro Precision: 0.64
Macro Recall: 0.62

Confusion Matrix on Test Data:
[[1274833  196761  159348]
 [ 328622  334050  206225]
 [ 348797  104379  969680]]


## Doing without smote

In [ ]:
# Loading the saved Random Forest model
best_rf = joblib.load("/content/drive/MyDrive/Project/4.Microsoft/New/rf_no_smote_tuned_model.joblib")

# Loading the test dataset
test_data = joblib.load('/content/drive/MyDrive/Project/4.Microsoft/New/df_test.joblib')

# Separateing the features and target from test data
X_test = test_data.drop('IncidentGrade', axis=1)
y_test = test_data['IncidentGrade']

In [ ]:
# Makeing predictions on the test data
y_test_pred = best_rf.predict(X_test)

# Evaluateing the saved model on the test data
print("\nClassification Report on Test Data:")
report = classification_report(y_test, y_test_pred, output_dict=True)
print(classification_report(y_test, y_test_pred))

macro_f1 = report['macro avg']['f1-score']
macro_precision = report['macro avg']['precision']
macro_recall = report['macro avg']['recall']

print("\nMacro-F1 Score: {:.2f}".format(macro_f1))
print("Macro Precision: {:.2f}".format(macro_precision))
print("Macro Recall: {:.2f}".format(macro_recall))
print("\nConfusion Matrix on Test Data:")
print(confusion_matrix(y_test, y_test_pred))


Classification Report on Test Data:
              precision    recall  f1-score   support

           0       0.65      0.78      0.71   1630942
           1       0.53      0.38      0.44    868897
           2       0.73      0.68      0.70   1422856

    accuracy                           0.66   3922695
   macro avg       0.64      0.62      0.62   3922695
weighted avg       0.65      0.66      0.65   3922695


Macro-F1 Score: 0.62
Macro Precision: 0.64
Macro Recall: 0.62

Confusion Matrix on Test Data:
[[1274833  196761  159348]
 [ 328622  334050  206225]
 [ 348797  104379  969680]]
